#!/bin/bash

# set -x

usage() {
        PROGNAME=$0
        cat <<- EOF

	$PROGNAME dev|prod

	EOF
                exit 1
}

init(){
	GREEN='\033[0;32m'
	RED='\033[0;31m'
	CYAN='\033[0;36m'
	NC='\033[0m' # No Color

	. ./config.ini
}

clearmsg(){
        msg=$1
        printf "${CYAN}${msg}${NC}\n"
}

generaldb_credential(){
    unset login
    prompt="Enter generaldb_mariadb ADMIN username: "
    read -p "$prompt" username
    
    unset password
    prompt="Enter generaldb_mariadb ADMIN password: "
    while IFS= read -p "$prompt" -r -s -n 1 char
    do
        if [[ $char == $'\0' ]]
        then
            break
        fi
        prompt='*'
        password+="$char"
    done
    echo
}

generaldb_credentials_file(){
        unset username
        unset password
        if [[ ! -f .generaldb_creds ]]; then
                echo "Credentials file cannot be found (.generaldb_creds)"
                exit 1
        fi

        . ./.generaldb_creds

        username=${mode}_username
        username=${!username}
        password=${mode}_password
        password=${!password}

        if [[ -z $username ]] || [[ -z password ]]; then
                echo "Credentials are empty (in .generaldb_creds)"
                exit 1
        fi
}

show_dbs(){
	echo "Showing Databases"
	command="show databases;"
	docker exec -it $generaldb_container_name mysql -u "$username" -p$password -e"$command"
}

show_db_users(){
	echo "Showing Users"
	command="SELECT User FROM mysql.user;"

	docker exec -it $generaldb_container_name mysql -u "$username" -p$password -e"$command"
}

main(){
	init

        mode=$1
        generaldb_container_name=${mode}_generaldb_container_name
        generaldb_container_name=${!generaldb_container_name}

	generaldb_credentials_file

	clearmsg "Content of /var/www"
	ls -1A /var/www
	echo

	clearmsg "Content of /projects"
	ls -1A /projects
	echo

	clearmsg "Databases"
	show_dbs
	echo

	clearmsg "Users"
	show_db_users
	echo

	clearmsg "Running containers"
	docker ps --format='{{.Names}}'
	echo

}

if [[ $# -ne 1 ]]
        then
                init
                usage
fi

main $@

