#!/bin/bash

# set -x

init(){
	. ./config.ini
}

generaldb_credential(){
    unset login
    prompt="Enter generaldb_mariadb ADMIN username: "
    read -p "$prompt" username
    
    unset password
    prompt="Enter generaldb_mariadb ADMIN password: "
    while IFS= read -p "$prompt" -r -s -n 1 char
    do
        if [[ $char == $'\0' ]]
        then
            break
        fi
        prompt='*'
        password+="$char"
    done
    echo
}

generaldb_credentials_file(){
	unset username
	unset password
	if [[ ! -f .generaldb_creds ]]; then
		echo "Credentials file cannot be found (.generaldb_creds)"
		exit 1
	fi

	. ./.generaldb_creds

	if [[ -z $username ]] || [[ -z password ]]; then
		echo "Credentials are empty (in .generaldb_creds)"
		exit 1
	fi
}

show_dbs(){
	echo "Showing Databases"
	command="show databases;"
	docker exec -it $generaldb_container_name mysql -u "$username" -p$password -e"$command"
	echo
}

show_db_users(){
	echo "Showing Users"
	command="SELECT User FROM mysql.user;"

	docker exec -it $generaldb_container_name mysql -u "$username" -p$password -e"$command"
	echo
}

main(){
	init
	#generaldb_credential
	generaldb_credentials_file

	echo "Content of /var/www"
	ls -1A /var/www
	echo

	echo "Content of /projects"
	ls -1A /projects
	echo

	echo "Databases"
	show_dbs
	echo

	echo "Container"
	docker ps --format='{{.Names}}'
	echo

}

main $@

