#!/bin/bash

# set -x

usage() {
        PROGNAME=$0
        cat <<- EOF

	Missing arguments
	$PROGNAME <project_name> <username> dev|prod

	EOF
        exit 1
}

init(){
	. ./config.ini
}

generaldb_credential(){
    unset login
    prompt="Enter generaldb_mariadb ADMIN username: "
    read -p "$prompt" username
    
    unset password
    prompt="Enter generaldb_mariadb ADMIN password: "
    while IFS= read -p "$prompt" -r -s -n 1 char
    do
        if [[ $char == $'\0' ]]
        then
            break
        fi
        prompt='*'
        password+="$char"
    done
    echo
}

generaldb_credentials_file(){
	mode=$1
        unset username
        unset password
        if [[ ! -f .${mode}_generaldb_creds ]]; then
                echo "Credentials file cannot be found (.generaldb_creds)"
                exit 1
        fi

        . ./.${mode}_generaldb_creds

        username=${mode}_username
        username=${!username}
        password=${mode}_password
        password=${!password}

        if [[ -z $username ]] || [[ -z password ]]; then
                echo "Credentials are empty (in .generaldb_creds)"
                exit 1
        fi
}

show_dbs(){
	echo "Showing Databases"
	command="show databases;"
	docker exec -it $generaldb_container_name mysql -u "$username" -p$password -e"$command"
	echo
}

delete_db_user(){
	command="REVOKE ALL PRIVILEGES, GRANT OPTION FROM \"$username_to_delete\";  DROP USER \"$username_to_delete\";"

	docker exec -it $generaldb_container_name mysql -u "$username" -p$password -e"$command"
}
delete_dbs(){
	command="DROP DATABASE \`$project_to_delete\`;"

	docker exec -it $generaldb_container_name mysql -u "$username" -p$password -e"$command"
}

delete_files(){
	if [[ -z $project_to_delete ]]; then
		"Variable \$project_to_delete is empty, cannot continue"
	fi
	rm -r /projects/$project_to_delete/*
	rmdir /projects/$project_to_delete/

	echo "About to remove /var/www/$project_to_delete/"
	rm -r /var/www/$project_to_delete/*
	rmdir /var/www/$project_to_delete/
}

show_db_users(){
	echo "Showing Users"
	command="SELECT User FROM mysql.user;"

	docker exec -it $generaldb_container_name mysql -u "$username" -p$password -e"$command"
	echo
}

main(){

        init

        project_to_delete=$1
	username_to_delete=$2
        #export $project_to_delete
        #export $username_to_delete
        mode=$3

        generaldb_container_name=${mode}_generaldb_container_name
        generaldb_container_name=${!generaldb_container_name}

        generaldb_credentials_file $mode

### 	while true; do
### 		echo
### 		prompt="Other things to delete? (yes/no) "
### 		read -p "$prompt" answer
### 		if [[ $answer =~ ^(yes|y|YES|Y)$ ]]; then
### 			execution
### 		else
### 			break
### 		fi
### 	done

### 	echo
### 	show_dbs
### 
### 	echo "Content of /var/www"
### 	ls -1A /var/www
### 	echo
### 
### 	echo "Content of /projects"
### 	ls -1A /projects
### 	echo
### 
### 	prompt="Enter name of project to delete: "
### 	read -p "$prompt" project_to_delete

	if [[ -z $project_to_delete ]]; then
		echo "Project name cannot be empty"
		exit 1
	fi

#	show_db_users
#	prompt="Enter username to delete: "
#	read -p "$prompt" username_to_delete

	delete_db_user
	show_db_users

	delete_dbs
	show_dbs

	docker stop $project_to_delete
	docker rm $project_to_delete

	delete_files
}

if [[ $# -ne 3 ]]
        then
                init
                usage
fi

main $@

