#!/bin/bash
# This script configures the developers group depending on the type of server
# It then connects as each users, so that homes are created
# Finally, it sets the developers group as primary group for each user
# 
# Version 1.0
# tbartolone 30/06/2020
set -x

usage() {
	PROGNAME=$0
	cat <<- EOF
	# lines must be indented with TAB

	This script saves the logs collection for a given container
	Missing arguments
	$PROGNAME <project_name>

	$credentials_path/.<project_name>.cnf
	[mysqldump]
	user=XXXXX
	password=XXXX
	
	EOF
	exit 1
}

init(){
	GREEN='\033[0;32m'
	RED='\033[0;31m'
	CYAN='\033[0;36m'
	NC='\033[0m' # No Color
	timestamp=$(date +\%Y\%m\%d-\%H\%M)

	. config.ini
}

go(){
	:
}

testexec(){
	:
}


main(){

	init

	project_name=$1
	# Move the credentials
	cp $credentials_path/.${project_name}.cnf $db_shared_path_host
	chown ${container_uid}:nogroup $db_shared_path_host/.${project_name}.cnf
	chmod 400 $db_shared_path_host/.${project_name}.cnf

	# Save the database and immediately delete credentials
	docker exec $generaldb_container_name bash -c "mysqldump --defaults-file=$db_shared_path_container/.${project_name}.cnf -v ${project_name} > $db_shared_path_container/${project_name}.sql" || exit 1
	rm -f $db_shared_path_host/.${project_name}.cnf

	# TGZ Wordpress website along with database backup
	tar -czvf $backups_path/${project_name}-${timestamp}.tgz $varwww_path/${project_name}/wordpress $db_shared_path_host/${project_name}.sql ${project_path}/${project_name}
#	/data/code/bara/ /root/backup/barabackup2

	# Delete database backup
	rm -f $db_shared_path_host/${project_name}.sql

### 	if [[ $1 = "go" ]]
### 		then
### 			init
### 			go
### 			testexec
### 		else
### 			init
### 			testexec
### 	fi
}

if [[ $# -eq 0 ]]
	then
		init
		usage
fi

main $@
