version: '3'

services:
  # proxy nginx
  reverse-proxy:
    container_name: reverse-proxy
    # do not touch this
    image: reverse-proxy:1.0
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 80:80
      - 443:443
    volumes:
        - /var/www/reverse-proxy/conf.d:/etc/nginx/conf.d
        - /var/www/reverse-proxy/certbot/conf:/etc/letsencrypt
        - /var/www/reverse-proxy/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    networks:
      - front
      - dmz

networks:
  front:
    name: front
  dmz:
    name: dmz
