version: '2'
services:
  {{new_project}}:
    image: docker.io/bitnami/wordpress:6.0.1
    #    ports:
    #      - '80:8080'
    #      - '443:8443'
    container_name: {{new_project}}
    volumes:
      - /var/www/{{new_project}}/wordpress:/bitnami/wordpress
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_DATABASE_HOST={{database}}
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=$new_username
      - WORDPRESS_DATABASE_PASSWORD=$new_password
      - WORDPRESS_DATABASE_NAME=$new_project
      - WORDPRESS_ENABLE_HTTPS=no
    networks:
      - front
      - back

networks:
  front:
    name: front
  back:
    name: back
