version: '2'
services:
  generaldb-dev:
    image: docker.io/bitnami/mariadb:10.3
    container_name: generaldb-dev
    volumes:
      - '/var/www/generaldb/dev/mariadb:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_USER=${MARIADB_ROOT_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
      - BITNAMI_DEBUG=false
    restart: always
    networks:
      - back

networks:
  back:
    name: back
